---
services:
  ################
  ### JELLYFIN ###
  ################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /mnt/bigDiskEnergy/container-data/cfgJF:/config
      - /mnt/bigDiskEnergy/media/TV:/tv
      - /mnt/bigDiskEnergy/media/Anime:/anime
      - /mnt/bigDiskEnergy/media/Movies:/movies
    ports:
      - 8096:8096
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped

  ##############
  ### SONARR ###
  ##############
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Melbourne
    volumes:
      - /mnt/bigDiskEnergy/container-data/cfgSonarr:/config
      - /mnt/bigDiskEnergy/media/TV:/tv
      - /mnt/bigDiskEnergy/media/Anime:/anime
      - /mnt/bigDiskEnergy/media/Downloads:/downloads
    ports:
      - 8989:8989
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped

  ##############
  ### RADARR ###
  ##############
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Melbourne
    volumes:
      - /mnt/bigDiskEnergy/container-data/cfgRadarr:/config
      - /mnt/bigDiskEnergy/media/Movies:/movies
      - /mnt/bigDiskEnergy/media/Downloads:/downloads
    ports:
      - 7878:7878
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped

  #################
  ### JELLYSEERR ##
  #################
  jellyseerr:
     image: fallenbagel/jellyseerr:latest
     container_name: jellyseerr
     environment:
       - PUID=1001
       - PGID=1001
       - LOG_LEVEL=debug
       - TZ=Asia/Tashkent
     ports:
       - 5055:5055
     volumes:
       - /mnt/bigDiskEnergy/container-data/cfgJellySeerr:/app/config
     restart: unless-stopped

  ##############
  ### NZBGET ###
  ##############
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Melbourne
      - NZBGET_USER=haioken
      - NZBGET_PASS=2420Shauri
    volumes:
      - /mnt/bigDiskEnergy/container-data/cfgNZBGet:/config
      - /mnt/bigDiskEnergy/media/Downloads:/downloads
    ports:
      - 6789:6789
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped

  ###################
  ### QBITTORRENT ###
  ###################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Melbourne
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/bigDiskEnergy/container-data/cfgQbit:/config
      - /mnt/bigDiskEnergy/media/Downloads:/downloads
    ports:
      - 6767:8080
      - 6881:6881
      - 6881:6881/udp
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped